### ISSUE TITLE
Error while logining: auth is failed

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Desamod/xKuCoinBot#1]
![image](https://github.com/user-attachments/assets/2e17d166-fda6-4904-93eb-c99a21e1fd13)

**Comment by Nord1cWarr1or** [comment]
@Desamod

**Comment by Desamod** [comment]
Most likely you specified the wrong referral link

**Comment by Nord1cWarr1or** [comment]
Да, спасибо
